"""
ingestion/models.py — Canonical data models.

Every piece of data that enters the pipeline is validated against
one of these models. This is your single source of truth for schema.

Key rules enforced here:
  - Timestamps are always UTC-aware datetimes
  - Prices are always float (use Decimal in production for real money)
  - Every model has a `source` field so you know where data came from
"""

from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, field_validator


class Tick(BaseModel):
    """A single trade or quote event from the price stream."""
    symbol: str
    timestamp: datetime
    price: float
    volume: int
    bid: Optional[float] = None
    ask: Optional[float] = None
    source: str  # e.g. "alpaca", "polygon", "kite"

    @field_validator("timestamp", mode="before")
    @classmethod
    def ensure_utc(cls, v):
        """Convert any timestamp to UTC. Reject naive datetimes."""
        if isinstance(v, str):
            v = datetime.fromisoformat(v.replace("Z", "+00:00"))
        if v.tzinfo is None:
            raise ValueError("Timestamp must be timezone-aware (UTC required)")
        return v.astimezone(timezone.utc)

    @field_validator("price")
    @classmethod
    def price_must_be_positive(cls, v):
        if v <= 0:
            raise ValueError(f"Price must be positive, got {v}")
        return v

    @field_validator("symbol")
    @classmethod
    def symbol_uppercase(cls, v):
        return v.upper().strip()


class NewsArticle(BaseModel):
    """A news headline or article relevant to one or more symbols."""
    title: str
    description: Optional[str] = None
    url: str
    published_at: datetime
    source_name: str
    symbols: list[str] = []  # tickers this article is relevant to

    @field_validator("published_at", mode="before")
    @classmethod
    def ensure_utc(cls, v):
        if isinstance(v, str):
            v = datetime.fromisoformat(v.replace("Z", "+00:00"))
        if isinstance(v, datetime) and v.tzinfo is None:
            v = v.replace(tzinfo=timezone.utc)
        return v

    @field_validator("symbols", mode="before")
    @classmethod
    def uppercase_symbols(cls, v):
        return [s.upper() for s in v]


class Fundamental(BaseModel):
    """Key fundamental data for a symbol (updated daily)."""
    symbol: str
    fetched_at: datetime
    pe_ratio: Optional[float] = None
    eps: Optional[float] = None
    revenue: Optional[float] = None
    market_cap: Optional[float] = None
    fifty_two_week_high: Optional[float] = None
    fifty_two_week_low: Optional[float] = None
    source: str = "screener"

    @field_validator("symbol")
    @classmethod
    def symbol_uppercase(cls, v):
        return v.upper().strip()


class Signal(BaseModel):
    """A trading signal generated by the signal engine."""
    symbol: str
    timestamp: datetime
    signal_type: str  # e.g., "sentiment", "volume", "pattern"
    value: str        # e.g., "positive", "breakout", "anomaly"
    confidence_score: Optional[float] = None
    source: str = "signal_engine"

    @field_validator("timestamp", mode="before")
    @classmethod
    def ensure_utc(cls, v):
        if isinstance(v, str):
            v = datetime.fromisoformat(v.replace("Z", "+00:00"))
        if getattr(v, "tzinfo", None) is None:
            raise ValueError("Timestamp must be timezone-aware (UTC required)")
        return v.astimezone(timezone.utc)

    @field_validator("symbol")
    @classmethod
    def symbol_uppercase(cls, v):
        return v.upper().strip()
